server:
  port: 8300
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vishalsin888/config-server
          clone-on-start: true
   